### ISSUE TITLE
Software Developer (Remote Working)

### ISSUE THREAD

**Issue by hikalkan** [volosoft/vs-home#1]
### Skills
* C#
* ASP.NET Core, Entity Framework Core
* Javascript, Typescript
* Single Page Applications (Angular or similar)
* Relational and Non-relational/NoSQL databases

And the tools and libraries around these technologies.

### Abilities & Interests
* OOP, Design Patterns, SOLID principles, Dependency Injection, Domain Driven Design, NLayer Architecture
* Microservice architecture, REST services, messaging
* Writing Automated Tests (unit/integration tests)
* Clean, readable and maintainable coding, continuous refactoring
* Following open source projects and trends, trying to be in
* English reading, writing and speaking.
* Ability to work remotely as part of a virtual team

### Job Description

* Participate in design & development of the [ABP framework](https://abp.io/) and modules.
* Documenting the framework ([example](https://abp.io/documents/abp/latest/Index)), writing articles/tutorials ([examples](https://medium.com/volosoft)).
* Developing applications based on the ABP framework.
* Participate in code reviews.

### Working Conditions
* Works remotely (home or another comfortable place).
* Flexible working hours in a day (totally 8 hours in a day, 5 days in a week).
* 15 days vacation in a year (3 weeks, including weekends).
* Vacations for national holidays in employee's country.
* Monthly payment (at the end of a worked month).

### How To Apply
Please contact to info@volosoft.com with the following informations:

* Your formal CV
* Sample source code parts you have written before (in C# and Javascript/Typescript). A public source code repository would be better.
* Have you heard or used the ABP (ASP.NET Boilerplate) framework before? Please share your experiences.

**Comment by edison1105** [comment]
I wanna have a try, but I am not good at speaking English.

**Comment by hikalkan** [comment]
Thank you. Can you send an email to info@volosoft.com and attach your CV if available.

**Comment by saulenriquejr** [comment]
I'd like to apply to this position, I'm a fan of ABP 👍

**Comment by hikalkan** [comment]
Sure, please, it's open for everyone :)

**Comment by guojq2com** [comment]
I wanna have a try, but I am not good at speaking English.

I am rookie and not used abp in projects.

**Comment by vahidcelik** [comment]
Hello, are there any partial working position like 2 or 3 day in a week?

**Comment by saulenriquejr** [comment]
sure, sounds good too

**Comment by hikalkan** [comment]
For this position, we are looking for a full time work.

**Comment by hikalkan** [comment]
I'm closing this position because we have collected enough CV and will start to evaluation. Thanks to everybody :)

**Comment by ghost** [comment]
> I'm closing this position because we have collected enough CV and will start to evaluation. Thanks to everybody :)

who got selected.... ?? I am also experimenting with aspnetboilerplate now

**Comment by hikalkan** [comment]
> who got selected

I can't declare yet since he has not started yet :)
