### ISSUE TITLE
Technical Support Engineer (.NET)

### ISSUE THREAD

**Issue by ebicoglu** [volosoft/vs-home#27]
## Knowledge & Abilities

- Expert in`.NET` technologies and proficient in `C#` language
- General knowledge of popular database systems and good knowledge of one database management system
- Basic knowledge of `CSS`, `JavaScript` and `HTML`
- Solution-oriented and willing to solve technical software issues
- Strong experience responding to critical developer-facing and executive-level escalations.
- Strong computer science/computer engineering fundamentals: Things change rapidly, and fundamentals are key to adapting and learning quickly.
- Experience working with teams developing `ASP.NET`, `Angular`, `Blazor`, `.NET MAUI` and microservices. 
- Curiosity, a passion for excellence, the ability to ask the right questions and the love of working as part of a team!
- Exceptional verbal, written and interpersonal communication skills: You will write, present to, and speak with developers and engineering colleagues regularly.
- Being familiar with the [ABP Framework](https://github.com/abpframework/abp) is a big plus!

## Job Description

- Providing technical support for the [ABP Framework](https://github.com/abpframework/abp) and [ABP Commercial](https://commercial.abp.io/)
- Technical support will be provided at [support.abp.io](https://support.abp.io), e-mail or via remote connection 
- Directing technical problems from users about our products to the software team
- Partially contribute to the [ABP Framework](https://github.com/abpframework/abp) or [ABP Commercial](https://commercial.abp.io/) by developing software
- Working 8 hours a day on weekdays

## About Our Company

* We develop libraries, frameworks and tools for open-source and commercial software developers
* Our open-source [ABP Framework](https://abp.io) project is used by thousands of software developers worldwide
* You can check out our products at [Volosoft.com](https://volosoft.com/)
* We strive to provide an environment where employees can work happily, motivated and productively

## Are you interested? 

* Please e-mail us at [hr@volosoft.com](mailto:hr@volosoft.com?subject=Technical-Support-Engineer-Application-2023) with the subject `Technical-Support-Engineer-Application-2023`

**Comment by 1nature** [comment]
I'd like to join your team. I will help you deliver the job expectations and you would like working with me.
