### ISSUE TITLE
QA & Test Engineer INTERN — 2024.10

### ISSUE THREAD

**Issue by ebicoglu** [volosoft/vs-home#38]
## Job Description  🛠️

- Detecting bugs, defects, regressions and verifying resolutions
- Testing use-cases and reporting the faults
- Checking final web apps against user-friendliness
- Designing, implementing, executing and debugging test cases and scripts
  

## Qualifications 🤹🏽

- Student in computer/software engineering or related IT departments or newly graduated
- Eager to become a Test Engineer in her/his career
- An understanding of web technologies
- Basic software development and troubleshooting skills
- Verbal and written English is required

  

## Working Conditions ⏲️

* Hybrid or fully remote working option
* 5 days a week, optional 09:00 — 18:00 or 08:00 — 17:00 working hours. No extra shifts!
* 15 working days of leave per year (3 weeks, including weekends)
* Travel and meal allowances, including for remote workers
* Salary is paid at the end of the month
* Company location:📍[Bakirkoy, Istanbul](https://g.page/Volosoft)  

## About Our Company 🏢

Volosoft is building **open-source** and **commercial** software development tools, libraries and **frameworks** for other developers. Our flagship project [ABP.io](https://github.com/abpframework/abp) is an open-source web application framework that reached ⭐13K stars on GitHub. We have a highly experienced team of **software architects** and solutions. There is a minimum business logic in our projects; hence, we highly focus on applying the best coding standards and cutting-edge development technologies. We love to share our experiences with the community by producing open-source software, writing articles, talking at global conferences and producing content for developers.  We only work on our own projects, which are not business logic intensive projects like software made in a certain sector such as banking, tourism, automotive, etc.

Check out the following links to learn more about our company:

🧷 https://abp.io — Our flagship project, which is open-source and has over 11K stars on [GitHub](https://github.com/abpframework/abp)
🧷 https://volosoft.com — Company's official website
🧷 https://aspnetboilerplate.com &  https://aspnetzero.com — Other projects we've been still working on
🧷 https://twitter.com/volosoftcompany
🧷 https://www.linkedin.com/company/volosoft
🧷 https://www.youtube.com/volosoft
🧷 https://www.instagram.com/volosoftcompany/
🧷 https://medium.com/volosoft
🧷 https://www.facebook.com/volosoftcompany
🧷 https://github.com/volosoft

## Applying for the Position  ✉️

You will send an e-mail to the HR.
📄 Add your CV as a PDF file to your e-mail.
🔖 The e-mail subject must be `TEST_ENGINEER_2024_10`.
📨 The e-mail must be sent to `hr@volosoft.com`.
▶️ [Click here to send an e-mail with your default email application ](mailto:hr@volosoft.com?subject=TEST_ENGINEER_2024_10).

**Comment by Sekolas** [comment]
I sended my cv to hr.
