### ISSUE TITLE
.NET Developer — 2024.11

### ISSUE THREAD

**Issue by ebicoglu** [volosoft/vs-home#40]
## Required Skills 🤹🏽

- **C# and ASP.NET Core** expertise.
- Blazor & MVC & .NET MAUI & EF Core knowledge.
- Knowledge of **JavaScript, basic HTML and CSS**.
- Familiarity with at least one database system (MS-SQL, MySQL, PostgreSQL, Oracle, etc...).
- Writing clean, understandable, and maintainable code.
- **Technical English** is a must.
- Graduated from **Computer Engineering or Software Engineering**.
- Minimum 1 year experience.
- Object-oriented programming, SOLID principles, Domain Driven Design, Multi-threading and Aspect-oriented programming knowledge is a plus.
- Kubernetes, Docker and Azure knowledge is a plus.
- ABP Framework knowledge is a plus.

---

## Job Description 🛠️

- You will be contributing to the development of [**ABP Platform**](https://abp.io/) and its underlying infrastructure.
- Implementing HTML content created by the design team into web applications.
- Maintaining and improving our **web apps**.
- Contributing to the framework's [**documentation**](https://docs.abp.io), writing technical articles, and tutorials. Examples: [Our documentation](https://abp.io/docs/) [Medium articlest](https://medium.com/volosoft), [Our community posts](https://community.abp.io), [Our blog](https://blog.abp.io).

---

## Working Conditions ⏲️

- Work hours: **Monday to Friday, 09:00–18:00** (or optionally 08:00–17:00). **No overtime!**
- **Hybrid or fully remote** working options.
- Our office is located in Atatürk Havalimanı Serbest Bölgesi. [📍See the location ](https://www.google.com/maps/place/Volosoft+Ltd.Sti/@40.9919121,28.8191698,17z/data=!3m1!4b1!4m5!3m4!1s0x14caa103aa268a89:0xf623f84e55f72076!8m2!3d40.9919081!4d28.8213638)

---

## About Us 🏢

- We develop **libraries, frameworks, and tools** for software developers, both open-source and commercial.
- Our open-source **ABP Framework** project, with **13.000 GitHub stars**, is actively used by tens of thousands of developers worldwide. 👉 [github.com/abpframework/abp](https://github.com/abpframework/abp).
- Visit [Volosoft.com](https://volosoft.com) to explore our other products.
- We work solely on our own projects, focusing on **state-of-the-art software development techniques** and global best practices rather than industry-specific projects (e.g., banking, tourism, healthcare).
- We strive to create an environment where our team members can work happily, stay motivated, and be productive.

---

## How To Apply? ✉️

Interested candidates can apply via email. Make sure to include **everything that sets you apart** in your CV.

- Attach your **CV in PDF format** to the email.
- Use the subject line: `DOTNET_DEVELOPER_2024_11`.
- Send the email to **`hr@volosoft.com`**.
- ▶️ [Click here to send your email via your default email application.](mailto:hr@volosoft.com?subject=DOTNET_DEVELOPER_2024_11)

**Comment by gonultasmf** [comment]
I sent my CV to HR :)

**Comment by engineerdavut** [comment]
Hi. I send my CV and my coverletter.

**Comment by gonultasmf** [comment]
I sent my CV to HR.

**Comment by emrepaksoy** [comment]
I sent my CV to HR
