### ISSUE TITLE
Senior .NET Developer (İstanbul, Türkiye)

### ISSUE THREAD

**Issue by hikalkan** [volosoft/vs-home#6]
## Bilgi ve Yetenekler

* C#
* ASP.NET Core, Entity Framework Core
* Relational ve Non-Relational/NoSQL veritabanları
* JavaScript, Typescript, HTML
* SPA (Angular v.s.) bilgisi artı olmakla beraber zorunlu değil 
* OOP, Design Patterns, SOLID principles, Dependency Injection, Domain Driven Design, NLayer Architecture
* Microservice architecture, REST services, messaging
* Automated Tests (unit/integration tests)
* Temiz, anlaşılabilir ve sürdürülebilir kodlama, sürekli refactoring
* Open source projeleri ve gidişatı takip edip içerisinde olma isteği
* Teknik İngilizce okuma (iyi derecede), yazma (iyi derecede) ve konuşma (orta derecede)

## İş Tanımı

* [ABP framework](https://abp.io/) ve modüllerinin geliştirilmesinde görev almak.
* Framework dokümantasyonuna ([örnek](https://docs.abp.io)) katkıda bulunmak, teknik makale ve tutorial yazmak ([örnekler](https://medium.com/volosoft)).
* ABP framework üzerine open source ya da ticari uygulamalar geliştirmek.

## Çalışma Şartları

* Konum: [Bakırköy, İstanbul](https://www.google.com/maps/place/Volosoft+Ltd.Sti/@40.9919121,28.8191698,17z/data=!3m1!4b1!4m5!3m4!1s0x14caa103aa268a89:0xf623f84e55f72076!8m2!3d40.9919081!4d28.8213638).
* Haftada 5 gün (hafta içi), 08-17 ya da 09-18 saatleri arasında çalışıyoruz (tercihe bağlı). Fazla mesai yapmıyoruz.
* Yılda 15 iş günü ücretli izin.
* SGK'ya ek olarak özel sağlık sigortası.
* Maaş dışında yıllık prim (şirketin karlılık durumuna ve performansa bağlı olarak).
* Yol ve yemek ücreti.

## Firmamız Hakkında

- Açık kaynak kodlu ve ticari olmak üzere yazılım geliştiriciler için library, framework ve araçlar geliştiriyoruz.
- Açık kaynak kodlu ABP framework projemiz dünyada onbinlerce geliştirici tarafından aktif kullanılıyor. Bakınız: https://github.com/aspnetboilerplate/aspnetboilerplate
- https://volosoft.com/ adresinden ürünlerimizi görebilirsiniz.
- Kendi ürünlerimiz dışında, müşteri bazlı işler yapmıyoruz.
- Bir yazılım geliştiricisinin mutlu, motive ve üretken çalışacağı bir ortam sağlamaya çalışıyoruz.

## İletişim

- İlgilenen arkadaşlar [hr@volosoft.com](mailto:hr@volosoft.com) adresine email atarak iletişime geçebilirler.

**Comment by mustafakakac** [comment]
2015 yılından beri projelerimde aspnetboilerplate kullanıyorum. 2015 yılında CLK firmasının ERP sistemin yazılmasında kullandım. Neredeyse tüm süreçlerini biliyorum. Volosoft ekibinde yer almak gerçekten en büyük hayallerimden biri. Umarım aradığınız kişi ben olurum.

Saygılarımla,

**Comment by hikalkan** [comment]
Teşekkürler Mustafa yorumun ve başvurun için. Başvurunu inceleyip email üzerinden dönüş yapacağız :)
