### ISSUE TITLE
.NET Developer (İstanbul, Türkiye)

### ISSUE THREAD

**Issue by hikalkan** [volosoft/vs-home#8]
## Bilgi ve Yetenekler

* C#
* ASP.NET Core, Entity Framework Core
* JavaScript, HTML
* OOP, SOLID principles, Dependency Injection, Domain Driven Design
* Automated Tests (unit/integration tests)
* Temiz, anlaşılabilir ve sürdürülebilir kodlama, sürekli refactoring
* İyi derecede teknik İngilizce okuma ve yazma
* En az 2 yıl profesyonel çalışma hayatı deneyimi

## İş Tanımı

* [ABP framework](https://abp.io/) ve modüllerinin geliştirilmesinde görev almak.
* Framework dokümantasyonuna ([örnek](https://docs.abp.io)) katkıda bulunmak, teknik makale ve tutorial yazmak ([örnekler](https://medium.com/volosoft)).
* ABP Framework üzerine open source ya da ticari uygulamalar geliştirmek.

## Çalışma Şartları

* Konum: [Bakırköy, İstanbul](https://www.google.com/maps/place/Volosoft+Ltd.Sti/@40.9919121,28.8191698,17z/data=!3m1!4b1!4m5!3m4!1s0x14caa103aa268a89:0xf623f84e55f72076!8m2!3d40.9919081!4d28.8213638).
* Haftada 5 gün (hafta içi), 08-17 ya da 09-18 saatleri arasında çalışıyoruz (tercihe bağlı). Fazla mesai yapmıyoruz.
* Yılda 15 iş günü ücretli izin.
* SGK'ya ek olarak özel sağlık sigortası.
* Maaş dışında yıllık prim (şirketin karlılık durumuna ve performansa bağlı olarak).
* Yol ve yemek ücreti.

## Firmamız Hakkında

- Açık kaynak kodlu ve ticari olmak üzere yazılım geliştiriciler için library, framework ve araçlar geliştiriyoruz.
- Açık kaynak kodlu ABP framework projemiz dünyada onbinlerce geliştirici tarafından aktif kullanılıyor. Bakınız: https://github.com/aspnetboilerplate/aspnetboilerplate
- https://volosoft.com/ adresinden ürünlerimizi görebilirsiniz.
- Kendi ürünlerimiz dışında, müşteri bazlı işler yapmıyoruz.
- Bir yazılım geliştiricisinin mutlu, motive ve üretken çalışacağı bir ortam sağlamaya çalışıyoruz.

## İletişim

- İlgilenen arkadaşlar [hr@volosoft.com](mailto:hr@volosoft.com) adresine email atarak iletişime geçebilirler.

**Comment by mustafa-korkmaz** [comment]
Remote is ilanlarinizi da bekliyoruz
